tap "homebrew/core"

brew "asdf"
brew "autoconf"
brew "automake"
brew "base64"
brew "bison"
brew "brotli"
brew "bzip2"
brew "coreutils"
brew "curl"
brew "curlie"
brew "diffstat"
brew "diffutils"
brew "docker"
brew "dwarfutils"
brew "ffmpeg"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gd"
brew "gettext"
brew "gh"
brew "git"
brew "git-lfs"
brew "gmp"
brew "gnu-tar"
brew "gnupg"
brew "gpg"
brew "grep"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "irssi"
brew "jpeg"
brew "lazygit"
brew "libevent"
brew "libpng"
brew "libtiff"
brew "libtool"
brew "m4"
brew "make"
brew "minikube"
brew "mkcert"
brew "mpdecimal"
brew "mpfr"
brew "mtr"
brew "neomutt"
brew "nasm"
brew "ncurses"
brew "neovim"
brew "nmap"
brew "node"
brew "nvm"
brew "openjdk@11"
brew "openssh"
brew "openssl@1.1"
brew "p7zip"
brew "pcre"
brew "pre-commit"
brew "readline"
brew "restic"
brew "rust"
brew "sha2"
brew "sha3sum"
brew "sqlite"
brew "tarsnap"
brew "tcping"
brew "tcptraceroute"
brew "tmux"
brew "tmuxinator"
brew "tree"
brew "w3m"
brew "watch"
brew "webp"
brew "wget"
brew "xz"
brew "zstd"

# macOS only section
if OS.mac?
  tap "homebrew/cask"
  tap "homebrew/cask-fonts"
  tap "homebrew/services"

  # Development tools
  cask "visual-studio-code"
  cask "sublime-text"
  cask "drawio"
  cask "wireshark"

  # Terminal tools
  cask "font-hack-nerd-font"
  cask "kitty"
  cask "xquartz"

  # Auth tools
  cask "1password"
  cask "authy"

  # Communication tools
  cask "signal"
  cask "slack"
  cask "zoom"

  # Browsers
  cask "brave-browser", no_quarantine: true
  cask "firefox"

  # Cloud services
  cask "mullvadvpn"
  cask "backblaze"

  # Utilities
  cask "coconutbattery"
  cask "macupdater"
  cask "keka"
  cask "microsoft-remote-desktop"

  #cask "trezor-suite"

  # Gaming
  cask "steam"
  cask "battle-net"

  # Virtualization / Emulation
  cask "crossover"
  cask "parallels" # For Windows
  brew "dosbox-x"

end

if OS.mac?
  brew "mas"
  mas "PCalc", id: 403504866
  mas "Amphetamine", id: 937984704
  mas "Remote Desktop", id: 409907375
  mas "Microsoft To Do", id: 1274495053
end
