#!/bin/zsh

# Function to print a section if the content is not empty
print_section() {
    local content="$1"
    local header="$2"

    if [[ -n "$content" ]]; then
        echo "-------------------------------"
        echo -e "\e[1m$header\e[0m"
        echo "-------------------------------"
        echo
        echo "$content"
        echo
    fi
}

# Initialize flag for showing all sections
show_all=false

# Parse options
while getopts "a" opt; do
  case $opt in
    a)
      show_all=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

# Print sections with inline commands
print_section "$(echo "source ~/.zshrc >/dev/null 2>&1; alias" | zsh)" "Aliases configured"
test -d ~/.scripts && print_section "$(find ~/.scripts -type f -executable -o -type l -executable)" "Scripts available in ~/.scripts"
test -d ~/.local/bin && print_section "$(find ~/.local/bin -type f -executable -o -type l -executable)" "~/.local/bin"
test -d /snap/bin && print_section "$(find /snap/bin -type f -executable -o -type l -executable)" "/snap/bin"
print_section "$(npm list -g --depth=0)" "npm/npx commands"
print_section "$(pipx list)" "pipx commands"
if [[ "$show_all" == true ]]; then
    test -d "$HOMEBREW_PREFIX/bin" && print_section "$(find $HOMEBREW_PREFIX/bin -type f -executable -o -type l -executable)" "$HOMEBREW_PREFIX/bin"
    test -d "/usr/local/bin" && print_section "$(find /usr/local/bin -type f -executable -o -type l -executable)" "/usr/local/bin"
fi

